---
# Download (only if not downloaded yet) & Install
- name: Zookeeper | Verify tar.gz is already downloaded
  stat:
    path: "/home/{{ hadoop_user }}/zookeeper-{{ zookeeper_version }}.tar.gz"
  register: st_zk_downloaded

- name: Zookeper | Download package
  get_url:
    url: "{{ zookeeper_url }}"
    dest: /home/{{ hadoop_user }}/
    remote_src: yes
    validate_certs: no
  when: st_zk_downloaded.stat.exists == False

- name: Zookeeper | Unzip Zk tar
  unarchive:
    src: "/home/{{ hadoop_user }}/zookeeper-{{ zookeeper_version }}.tar.gz"
    dest: "/opt/"
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"
    copy: no

- name: Zookeeper | Ensure owner & group 
  file: 
    path: "{{ zookeeper_install_dir }}"
    state: directory
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"
    recurse: yes

- name: Zookeeper | Ensure ZK folder exists
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"
  with_items:
    - "{{ zookeeper_datadir }}"
    - "{{ zookeeper_logdir }}"

- name: Zookeeper | Overwrite zoo.conf
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_install_dir }}/conf/zoo.cfg"
    force: yes
  notify:
    - Zookeeper | restart zookeeper

- name: Zookeeper | Overwrite myid
  template:
    src: myid.j2
    dest: "{{ zookeeper_datadir }}/myid"
    force: yes
  notify:
    - Zookeeper | restart zookeeper
