---
- include: core.yml

- name: Hadoop | Create masters file
  template:
    src: masters.j2
    dest: "{{ hadoop_home }}/etc/hadoop/masters"
    force: yes


- name: Hadoop | Create slaves file
  template:
    src: slaves.j2
    dest: "{{ hadoop_home }}/etc/hadoop/slaves"
    force: yes




