---
# Folders
- name: Hadoop | Verify the namenode dir
  stat:
    path: "{{ hadoop_namenode_dir }}"
  register: st_namenode_dir

- name: Hadoop | Create namenode dir
  file:
    path: "{{ hadoop_namenode_dir }}"
    state: directory
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"
  when: st_namenode_dir.stat.exists == False

- name: Hadoop | Verify the namesecondary dir
  stat:
    path: "{{ hadoop_namesecondary_dir }}"
  register: st_namesecondary_dir

- name: Hadoop | Create namesecondary dir
  file:
    path: "{{ hadoop_namesecondary_dir }}"
    state: directory
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"
  when: st_namesecondary_dir.stat.exists == False

- name: Hadoop | Verify the datanode dir
  stat:
    path: "{{ hadoop_datanode_dir }}"
  register: st_datanode_dir

- name: Hadoop | Create datanode dir
  file:
    path: "{{ hadoop_datanode_dir }}"
    state: directory
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"
  when: st_datanode_dir.stat.exists == False 
