# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

API_VERSION     = 2
VB_NUM_CPU      = 1
VB_NUM_MEM      = 2048
BOX             = "ARTACK/debian-jessie"

Vagrant.configure(API_VERSION) do |config|
  
  config.vm.define "node1" do |node1|

    node1.ssh.username = 'root'
    node1.ssh.password = 'vagrant'
    node1.vm.box = BOX
    node1.vm.network "private_network", ip: "192.168.33.10"
    node1.vm.hostname = 'node1'
    node1.vm.network :forwarded_port, guest: 22, host: 2221, id: 'ssh'
    
    node1.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", VB_NUM_MEM]
          vb.customize ["modifyvm", :id, "--cpus", VB_NUM_CPU]
    end

  end

  config.vm.define "node2" do |node2|
    
    node2.ssh.username = 'root'
    node2.ssh.password = 'vagrant'
    node2.vm.box = BOX
    node2.vm.network "private_network", ip: "192.168.33.11"
    node2.vm.hostname = 'node2'
    node2.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh'

    node2.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", VB_NUM_MEM]
          vb.customize ["modifyvm", :id, "--cpus", VB_NUM_CPU]
    end

  end

  config.vm.define "node3" do |node3|

    node3.ssh.username = 'root'
    node3.ssh.password = 'vagrant'
    node3.vm.box = BOX
    node3.vm.network "private_network", ip: "192.168.33.12"
    node3.vm.hostname = 'node3'
    node3.vm.network :forwarded_port, guest: 22, host: 2223, id: 'ssh'

    node3.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", VB_NUM_MEM]
          vb.customize ["modifyvm", :id, "--cpus", VB_NUM_CPU]
    end

  end 

end
