---
# hive hosts (clients) machines
hive_hosts: [ node1 ]

# Configuration
hadoop_user: hadoop
hive_version: 2.1.1
hadoop_home: "/opt/hadoop-{{ hadoop_version }}"
hive_home: "/opt/apache-hive-{{ hive_version }}-bin"
hive_download_url: "http://ftp.cixug.es/apache/hive/hive-{{ hive_version }}/apache-hive-{{ hive_version }}-bin.tar.gz"
hive_env_vars:
  - { prefix: "export HIVE_HOME", sufix: "={{ hive_home }}" }
  - { prefix: "export HIVE_CONF_DIR", sufix: "={{ hive_home }}/conf" }
  - { prefix: "export PATH=$PATH:$HIVE_HOME/bin", sufix: ""}

