---
version: '2'
services:

  node1:
    image: gkrlodebian
    hostname: node1
    ports:
      - "2221:22"
    networks:
      mynet:
        ipv4_address: 192.168.33.10

  node2:
    image: gkrlodebian
    hostname: node2
    ports:
      - "2222:22"
    networks:
      mynet:
        ipv4_address: 192.168.33.11

  node3:
    image: gkrlodebian
    hostname: node3
    ports:
      - "2223:22"
    networks:
      mynet:
        ipv4_address: 192.168.33.12

  node4:
    image: gkrlodebian
    hostname: node4
    ports:
      "2224:22"
    networks:
      mynet:
        ipv4_address: 192.168.33.13

networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.33.0/24
