---
# Download (only if not downloaded yet) & Install
- name: HBase | Verify tar.gz is already downloaded
  stat:
    path: "/home/{{ hadoop_user }}/hbase-{{ hbase_version }}-bin.tar.gz"
  register: st_hbase_downloaded

- name: HBase | Download hbase
  get_url:
    url: "{{ hbase_download_url }}"
    dest: /home/{{ hadoop_user }}/
    remote_src: yes
    validate_certs: no
  when: st_hbase_downloaded.stat.exists == False

- name: HBase | Unzip hbase package
  unarchive:
    src: "/home/{{ hadoop_user }}/hbase-{{ hbase_version }}-bin.tar.gz"
    dest: /opt/
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"
    copy: no

# Set envs variables in ~/.bashrc & profile
- name: HBase | Remove hadoop env vars
  lineinfile:
    path: "/home/{{ hadoop_user }}/.bashrc"
    regexp: "^{{item['prefix']}}"
    state: absent
  with_items: "{{ hbase_env_vars }}"

- name: HBase | Add hadoop envs ~/.bashrc
  lineinfile:
    path: "/home/{{ hadoop_user }}/.bashrc"
    line: "{{ item['prefix']+item['sufix'] }}"
    insertafter: EOF
    state: present
  with_items: "{{ hbase_env_vars }}"

- name: HBase | Copy .bashrc to /etc/profile
  shell: "cp /home/{{ hadoop_user }}/.bashrc /etc/profile"
  args:
    executable: /bin/bash

- name: HBase | Copy .bashrc to ~/.profile
  shell: "cp /home/{{ hadoop_user }}/.bashrc ~/.profile"
  args:
    executable: /bin/bash

# Config files
- name: HBase | Ensure hive-env.sh is created
  file:
    path: "{{ hbase_home }}/conf/hbase-env.sh"
    state: touch
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"

- name: HBase | Remove hadoop_home in hbase-env.sh
  lineinfile:
    path: "{{ hbase_home }}/conf/hbase-env.sh"
    regexp: "^{{ item['prefix'] }}"
    state: absent
  with_items: "{{ hbase_conf_env_vars }}"

- name: HBase | Set hadoop_home in hbase-env.sh
  lineinfile:
    path: "{{ hbase_home }}/conf/hbase-env.sh"
    line: "{{ item['prefix'] + item['sufix'] }}"
    insertbefore: BOF
    state: present
  with_items: "{{ hbase_conf_env_vars }}"

- name: HBase | Create hbase-site.xml
  template:
    src: hbase-site.xml.j2
    dest: "{{ hbase_home }}/conf/hbase-site.xml"
    force: yes

- name: Hadoop | Create regionservers file
  template:
    src: regionservers.j2
    dest: "{{ hbase_home }}/conf/regionservers"
    force: yes