---
# Download (only if not downloaded yet) & Install
- name: Phoenix | Verify tar.gz is already downloaded
  stat:
    path: "/home/{{ hadoop_user }}/apache-phoenix-{{ phoenix_version }}-HBase-1.2-bin.tar.gz"
  register: st_phoenix_downloaded

- name: Phoenix | Download hbase
  get_url:
    url: "{{ phoenix_download_url }}"
    dest: /home/{{ hadoop_user }}/
    remote_src: yes
    validate_certs: no
  when: st_phoenix_downloaded.stat.exists == False

- name: Phoenix | Unzip phoenix package
  unarchive:
    src: "/home/{{ hadoop_user }}/apache-phoenix-{{ phoenix_version }}-HBase-1.2-bin.tar.gz"
    dest: /opt/
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"
    copy: no

- name: Phoenix | Ensure owner & group 
  file: 
    path: "{{ phoenix_home }}"
    state: directory
    group: "{{ hadoop_user }}"
    owner: "{{ hadoop_user }}"
    recurse: yes