---
# Hadoop hosts machines
regionserver_hosts: [ node2, node3, node4 ]
hbase_master_host: node1
namenode_host: node1
zookeeper_hosts: [ node1 ]
zookeeper_datadir: /var/lib/zookeeper
zookeeper_clientport: 2181

# Configuration
hbase_version: 1.2.5
hadoop_user: hadoop
hbase_home: "/opt/hbase-{{ hbase_version }}"
hbase_download_url: "http://apache.rediris.es/hbase/stable/hbase-{{ hbase_version }}-bin.tar.gz"
hbase_manages_zk: "false"
java_home: "/usr/lib/jvm/java-8-oracle/"

#Lists of conf vars
hbase_env_vars:
  - { prefix: "export HBASE_HOME", sufix: "={{ hbase_home }}" }
  - { prefix: "export PATH=$PATH:$HBASE_HOME/bin", sufix: ""}

hbase_conf_env_vars:
  - { prefix: "export JAVA_HOME", sufix: "={{ java_home }}" }
  - { prefix: "export HBASE_MANAGES_ZK", sufix: "={{ hbase_manages_zk }}"}



